apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    name: nginx-pod
    app: proxy-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: nginx-pod
      app: proxy-app
  template:
    metadata:
      name: nginx-pod
      labels:

        name: nginx-pod
        app: proxy-app


    spec:
      containers:
        - name: nginx
          image: nginx:1.14
          ports:
            - containerPort: 80
